[package]
name = "universal-hash"
version = "0.5.0" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Trait for universal hash functions"
documentation = "https://docs.rs/universal-hash"
repository = "https://github.com/RustCrypto/traits"
keywords = ["crypto", "mac"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2018"

[dependencies]
generic-array = "0.14"
crypto-common = { version = "0.1", features = ["subtle"], path = "../crypto-common" }

[features]
std = []

[package.metadata.docs.rs]
all-features = true
